#include "../include/ladder.h"
#include "plcLib.h"
#include <fstream>
#include <string>

void generateKeilCode(const LadderProgram& program, const std::string& filename) {
    std::ofstream file(filename);
    file << "// Generated by LDmicro-TUI with plcLib elements\n";
    file << "#include \"plcLib.h\"\n\n";
    file << "void setup() {\n";
    for (const auto& rung : program.rungs) {
        for (const auto& el : rung.elements) {
            if (el.type == ElementType::COIL) {
                file << "    out(" << el.name << ", true);\n";
            }
        }
    }
    file << "}\n\nvoid loop() {}\n";
    file.close();
}